apps/usuario/urls.py
from django.urls import path,include,reverse_lazy
from django.conf.urls import url
from apps.usuario.views import index, UsuarioList, RegistroUsuario , UserUpdate , UserDelete


app_name='administracion'

urlpatterns= (
    path('', index, name='index'),
    url(r'^listar/', UsuarioList.as_view(), name='listar'),
    url(r'^registrar/', RegistroUsuario.as_view(), name="registrar"),
    url(r'^editar/(?P<pk>\d+)/$',UserUpdate.as_view(),name='usuario_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$',UserDelete.as_view(),name='usuario_eliminar'),
)


#path('',base),

project01/urls.py
"""project01 URL Configuration

La lista `urlpatterns` enruta las URL a las vistas. Para más información por favor vea:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Ejemplos:
Vistas de funciones
    1. Agregar una importación: desde las vistas de importación my_app
    2. Agregue una URL a urlpatterns: ruta ('', views.home, name = 'home')
Vistas basadas en clase
    1. Agregue una importación: desde other_app.views import Inicio
    2. Agregue una URL a urlpatterns: path ('', Home.as_view (), name = 'home')
Incluyendo otro URLconf
    1. Importe la función include (): desde django.urls import include, path
    2. Agregue una URL a urlpatterns: ruta ('blog /', include ('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from project01.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name = 'index'),
    path('usuario/',include('apps.usuario.urls',namespace='usuario')),
    path('us/',include('apps.us.url',namespace='us')),
    path('rol/', include(('apps.rol.urls','rol'), namespace='rol')),
    path('proyecto/', include('apps.proyecto.urls', namespace='proyecto')),


    path('',LoginView.as_view(),{'template_name':'templates/registration/login.html'}, name='login'),
    path('logout/',logout_then_login, name='logout'),
    url(r'^reset/password_reset',PasswordResetView.as_view(),{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    path('reset/password_reset_done',PasswordResetDoneView.as_view(),{'template_name':'registration/password_reset_done'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',PasswordResetConfirmView.as_view(),{'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'reset/done',PasswordResetCompleteView.as_view(),{'template_name':'registration/password_reset_complete.html'},name='password_reset_complete'),
]

""""
    se tienen las direcciones de:
    -usuario
    -rol
    -Login
    -Recuperacion de contraseña que consta de:
    
    *password reset done: envia un correo, con un enlace para reestablecer la contraseña, al correo que el usuario proporciona 
    *password reset email: mensaje que contiene el correo recibido con el enlace
    *password reset confirm: proporciona el reestablecimiento, de contraseña una vez accedido al enlace
    *password reset complete: indica al usuario que la contraseña se reestablecio correctamente
"""

apps/usuario/models.py
from django.db import models


# Create your models here.
class Usuario(models.Model):
    username= models.CharField(max_length=50)
    passwordd=models.CharField(max_length=50)
    nombres=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    # Este tiene que ser del tipo Rol pero como no tengo el modelo Rol,mientras asi
    rol_de_sistema=models.CharField(max_length=50)
    estado=models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.Usuario.nombres)

apps/usuario/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django import forms
from django.db.models import Q

"""
    Formulario:
    parametros:
    1. hereda de forms.Modelform
	
	groups: Filtra los grupos que seran
	utilizados en el sistema

    Class Meta:
    se especifican los campos que seran que
    seran añadidos o modificados:
	* username,
	* first_name,
	* last_name,
	* email,
	* groups,
"""
class RegistroForm(UserCreationForm):

	groups = forms.ModelChoiceField(queryset=Group.objects.filter(~Q(permissions__content_type__model="permiso")), required=True,widget=forms.Select(attrs={'class':'form-control'}))

	class Meta:
		model = User
		fields = [
			'username',
			'first_name',
			'last_name',
			'email',
			'groups',
			]
		labels = {
			'username': 'Nombre de usuario',
			'first_name': 'Nombres',
			'last_name': 'Apellidos',
			'email': 'Correo',
			'groups': 'Roles',
			}
			

	
	def save(self, commit=True):
		user = super(RegistroForm, self).save(commit=False)
		if commit:
			user.save()
		return user



		widgets= {
				'username': forms.TextInput(attrs={'class':'form-control'}),
				'first_name': forms.TextInput(attrs={'class':'form-control'}),
				'last_name': forms.TextInput(attrs={'class':'form-control'}),
				'email': forms.EmailField(attrs={'class':'form-control'}),
			}

apps/usuario/views.py
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView , UpdateView , DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from apps.miembros.models import Miembro
from apps.usuario.forms import RegistroForm

# Create your views here.
@login_required
def index(request):
    """
    Metodo que da bienvenida  al ususario . una vez validado el login
    """
    return render(request, "usuario/bien.html")


# return HttpResponse("esta es una prueba de login de acceso")

"""
   Listas basadas en Clases, ListView. Esta vista contendra la lista de usuarios del sistema
"""


class UsuarioList(PermissionRequiredMixin,ListView):
    model = User
    template_name = 'usuario/usuario_list.html'
    permission_required = 'auth.change_user'

    def get_context_data(self, **kwargs):
        # sobreescibe el contexto
        context = super(ListView, self).get_context_data(**kwargs)
        # Crea una lista de usuarios filtrando solo a los activos
        # usuariosLista = User.objects.all().filter(is_active=True)
        usuariosLista = User.objects.all().order_by("id")
        #Excluye el usuario Anonimo que genera django o django-guardian
        usuariosLista = usuariosLista.exclude(username="AnonymousUser")
        # Si es un usuario normal le excluye la lista de los usuarios Administradores
        # if -- falta condicion de que el usuario normal no vea los administradores---
        #   for admin in User.objects.filter(groups__name="Administrador"):
        #        usuariosLista = usuariosLista.exclude(id=admin.id)
        # Sobreescribe contexto object_list con la lista de usuarios filtrada
        context['object_list'] = usuariosLista
        return context


"""
   Esta Vista coontendra El formulario para el registro de Usuarios del sistema
"""


class RegistroUsuario(PermissionRequiredMixin, CreateView ):

    model = User
    template_name = "usuario/registrar.html"
    form_class = RegistroForm
    permission_required = 'auth.add_user'

    def form_valid(self, form):
        """
        Para asignar el usuario a un Rol ya cargado
        **Parametros**
           1. self: referencia al objeto
           2. form: Formulario de validacion del usuario
           **Retorna:** response: Formulario Valido
           """
        response = super(RegistroUsuario, self).form_valid(form)
        username=form.cleaned_data['username']
        rol = form.cleaned_data['groups']
        print(rol)
        print(username)
        g = Group.objects.get(name=rol) #Retorno el rol del modelo
        g.user_set.add(self.object) #Agrego el rol al usuario
        return response

    def get_success_url(self):
        """
        **Parametros**
        1. self: referencia al objeto
        **Retorna:** url del ListarUsuario
        """
        return reverse_lazy('usuario:listar')


class UserUpdate(PermissionRequiredMixin,UpdateView):
    model = User
    template_name = "usuario/registrar.html"
    form_class = RegistroForm
    permission_required = 'auth.change_user'

    def form_valid(self, form):
        """
        Para asignar el usuario a un Rol ya cargado
        **Parametros**
           1. self: referencia al objeto
           2. form: Formulario de validacion del usuario
           **Retorna:** response: Formulario Valido
           """
        response = super(UserUpdate, self).form_valid(form)
        #Extraigo los datos que recibo del formulario
        username=form.cleaned_data['username']
        rol = form.cleaned_data['groups']
        print(rol)
        print(username)
        #Retorno el rol del modelo
        g = Group.objects.get(name=rol)
        #Elimino mi grupo asociado al usuario
        print("HOLA MUNDO")
        print(self.object)
        usuario = User.objects.get(username=username)
        usuario.groups.clear()
        #Agrego el nuevo rol al usuario
        g.user_set.add(self.object)
        return response

    success_url = reverse_lazy('usuario:listar')


"""class UserDelete(PermissionRequiredMixin,UpdateView):
    model = User
    template_name = 'usuario/usuario_delete.html'
    form_class = RegistroForm
    permission_required = 'auth.change_user'
    
    def form_valid(self, form):
        response = super(UserDelete, self).form_valid(form)
        #Extraigo los datos que recibo del formulario
        usuario=self.object
        print("Usuario: ",self.object)
        print("Antes...")
        print(usuario.is_active)
        print("Despues...")
        usuario.is_active=False
        print(usuario.is_active)
        return response

    success_url = reverse_lazy('usuario:listar')

"""



class UserDelete(PermissionRequiredMixin,DeleteView):
    model = User
    template_name = 'usuario/usuario_delete.html'
    permission_required = 'auth.delete_user'
    success_url = reverse_lazy('usuario:listar')

templates/usuario/bien.html
{% extends 'base/base.html' %}

{% block title %}Gestor de Proyectos{% endblock %}



{% block content %}
    <h1 >Hola {{ request.user }}</h1>
{% endblock %}

templates/usuario/loguearse.html
{% extends 'base/base.html' %}

{% block title %}Usuario{% endblock %}

templates/usuario/registrar.html
{% extends 'base/base.html'%}

{% block content%}
    <div class="col-md-8 col-md-offset-1">
            {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    </div>
<form method = "post">
    {%csrf_token%}
    <div class="col-md-10">
        {{form.as_p}}
        <input class="btn btn-primary btn-large" type="submit" value="Guardar"/>
        <a class="btn btn-default" href="{% url 'usuario:listar' %}">Cancelar</a>
    </div>
</form>
{% endblock %}

templates/usuario/usuario_delete.html
{% extends 'base/base.html' %}

{% block content %}
<div style="text-align: center">
    <form method="post">
        {% csrf_token %}
        <h3>¿Desea Eliminar el registro de {{ object.first_name }}? </h3>
        <button class="btn btn-danger" type="submit">Si, eliminar </button>
        <a class="btn btn-default" href="{% url 'usuario:listar' %}">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/usuario/usuario_list.html
{% extends 'base/base.html' %}
{% block title %}Lista de Usuarios{% endblock %}
{% block content %}
<div class="table-responsive" style="max-height: 70vh; overflow-y: scroll;">
<table class="table table-bordered">
    <thead>
        <tr>
            <td>id</td>
            <td>Nombre de Usuario</td>
            <td>Nombres</td>
            <td>Apellidos</td>
            <td>Rol de Sistema</td>
            <td>Estado</td>
            <td>Opciones</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
                {% for usuario in object_list %}

                        <tr>
                            <!-- VERSION 2.0 -->
                            {% if usuario.groups.all %}
                                <td>{{usuario.id }}</td>
                                <td>{{usuario.username}}</td>
                                <td>{{usuario.first_name}}</td>
                                <td>{{usuario.last_name}}</td>
                                {% for user_group in usuario.groups.all %}
                                    <td>{{user_group}}</td>
                                {%endfor%}
                                {% if usuario.is_active %}
                                    <td>Activo</td>
                                {% else %}
                                    <td>Desactivado</td>
                                {% endif %}
                                <td>
                                    <a class="btn btn-primary" href="{%  url 'usuario:usuario_editar' usuario.id %}"> Editar</a>
                                    <a class="btn btn-danger" href="{% url 'usuario:usuario_eliminar' usuario.id %}">Eliminar</a>
                                </td>
                            {% endif %}
                      

                        <!-- VERSION 1.0
                             <td>{{usuario.id }}</td>
                            <td>{{usuario.username}}</td>
                            <td>{{usuario.first_name}}</td>
                            <td>{{usuario.last_name}}</td>
                        
                            
                            {% if usuario.groups.all %}
                                {% for user_group in usuario.groups.all %}
                                     <td>{{user_group}}</td>
                                {%endfor%}
                            {% else %}
                                <td>Superusuario</td>
                            {% endif %}
                       
                            {% if usuario.is_active %}
                                    <td>Activo</td>
                            {% else %}
                                    <td>Desactivado</td>
                            {% endif %}
                            <td>
                                <a class="btn btn-primary" href="{%  url 'usuario:usuario_editar' usuario.id %}"> Editar</a>
                                <a class="btn btn-danger" href="{% url 'usuario:usuario_eliminar' usuario.id %}">Eliminar</a>
                            </td>
                        -->
                        </tr>
                    {%endfor%}
            {% else %}
                <h1> No hay registros de usuarios </h1>
            {% endif %}
        </tbody>
    </table>
</div>
<a class="btn btn-primary" href="{% url 'usuario:registrar' %}">Registrar Usuario</a>
{% endblock%}