apps/proyecto/urls.py
from django.urls import include, re_path
from django.conf.urls import url
from .views import verifica_permiso_listar, verifica_permiso_detalle, verifica_permiso_modificar, \
    verifica_permiso_eliminar, verifica_permiso_crear, ver_kanban, CambiarFase_der,verifica_permiso_cabiarUsuario,CambiarEstado,\
    finalizar_us,listarUSfinalizados
#from .views import proyecto, verifica_permiso_detalle, proyectoList, \
#   ProyectoUpdate, ProyectoDelete, ver_kanban, RegistroProyecto, verifica_permiso_listar
app_name = 'proyecto'

urlpatterns = [
    re_path(r'^listar/', verifica_permiso_listar, name='listar'),
    re_path(r'^registrar/', verifica_permiso_crear, name="registrar"),
    re_path(r'^(?P<pk>\d+)/detalle/$', verifica_permiso_detalle , name='index'),
    re_path(r'^editar/(?P<pk>\d+)$', verifica_permiso_modificar, name='editar'),
    re_path(r'^eliminar/(?P<pk>\d+)$', verifica_permiso_eliminar, name='eliminar'),

    url(r'^(?P<pk>\d+)/rolProyecto/', include('apps.rolDeProyecto.urls', namespace='rolProyecto')),
    url(r'^(?P<pk>\d+)/miembro/', include('apps.miembros.urls', namespace='miembro')),
    url(r'^(?P<pk>\d+)/us/', include('apps.us.url', namespace='us')),
    url(r'^(?P<pk>\d+)/tablero_Kanban/$', ver_kanban, name="kanban"),
    url(r'^(?P<pk>\d+)/tablero_Kanban/cambiar_usuario/(?P<tmid>\d+)$', verifica_permiso_cabiarUsuario, name="cambiarUsuario"),
    url(r'^(?P<pk>\d+)/sprint/', include('apps.sprint.urls', namespace='sprint')),
    url(r'^(?P<pk>\d+)/tipous/', include('apps.tipous.urls', namespace='tus')),

    url(r"^(?P<pk>\d+)/tablero/cambiar_fase/(?P<uid>\d+)$", CambiarFase_der.as_view(), name="cambiar_fase"),
    url(r"^(?P<pk>\d+)/cambiar_estado/", CambiarEstado.as_view(), name="cambiar_estado"),
    url(r"^(?P<pk>\d+)/finalizar_user_story/(?P<tmid>\d+)$", finalizar_us.as_view(), name="finalizar_us"),
    url(r"^(?P<pk>\d+)/Release_Backlog/$", listarUSfinalizados.as_view(), name="release_backlog"),
]

"""
urlpatterns = [
    re_path(r'listar/', verifica_permiso_listar, name='listar'),
    re_path(r'^registrar/', RegistroProyecto.as_view(), name="registrar"),
    re_path(r'^(?P<pk>\d+)/detalle/$', verifica_permiso_detalle , name='index'),
    re_path(r'^editar/(?P<pk>\d+)$', ProyectoUpdate.as_view(), name='editar'),
    re_path(r'^eliminar/(?P<pk>\d+)$', ProyectoDelete.as_view(), name='eliminar'),

    url(r'^(?P<pk>\d+)/rolProyecto/', include('apps.rolDeProyecto.urls', namespace='rolProyecto')),
    url(r'^(?P<pk>\d+)/miembro/', include('apps.miembros.urls', namespace='miembro')),
    url(r'^(?P<pk>\d+)/us/', include('apps.us.url', namespace='us')),
    url(r'^(?P<pk>\d+)/tablero Kanban/$', ver_kanban, name="kanban"),
    url(r'^(?P<pk>\d+)/sprint/', include('apps.sprint.urls', namespace='sprint')),
    url(r'^(?P<pk>\d+)/tus/', include('apps.tipous.urls', namespace='tus')),
]
"""

apps/rol/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import Group
from apps.rol.views import RolesList,RolDelete,crear_rol_view,RolModify
urlpatterns = [
    url(r'^listar/',RolesList.as_view(),name='listar'),
    url(r'^eliminar/(?P<pk>\d+)/$',RolDelete.as_view(),name='rol_eliminar'),
    url(r'^crear/', crear_rol_view, name='crear'),
    url(r'^modificar/(?P<pk>\d+)/$', RolModify.as_view(model=Group,), name='rol_modificar'),
]

project01/urls.py
"""project01 URL Configuration

La lista `urlpatterns` enruta las URL a las vistas. Para más información por favor vea:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Ejemplos:
Vistas de funciones
    1. Agregar una importación: desde las vistas de importación my_app
    2. Agregue una URL a urlpatterns: ruta ('', views.home, name = 'home')
Vistas basadas en clase
    1. Agregue una importación: desde other_app.views import Inicio
    2. Agregue una URL a urlpatterns: path ('', Home.as_view (), name = 'home')
Incluyendo otro URLconf
    1. Importe la función include (): desde django.urls import include, path
    2. Agregue una URL a urlpatterns: ruta ('blog /', include ('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from project01.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name = 'index'),
    path('usuario/',include('apps.usuario.urls',namespace='usuario')),
    path('us/',include('apps.us.url',namespace='us')),
    path('rol/', include(('apps.rol.urls','rol'), namespace='rol')),
    path('proyecto/', include('apps.proyecto.urls', namespace='proyecto')),


    path('',LoginView.as_view(),{'template_name':'templates/registration/login.html'}, name='login'),
    path('logout/',logout_then_login, name='logout'),
    url(r'^reset/password_reset',PasswordResetView.as_view(),{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    path('reset/password_reset_done',PasswordResetDoneView.as_view(),{'template_name':'registration/password_reset_done'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',PasswordResetConfirmView.as_view(),{'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'reset/done',PasswordResetCompleteView.as_view(),{'template_name':'registration/password_reset_complete.html'},name='password_reset_complete'),
]

""""
    se tienen las direcciones de:
    -usuario
    -rol
    -Login
    -Recuperacion de contraseña que consta de:
    
    *password reset done: envia un correo, con un enlace para reestablecer la contraseña, al correo que el usuario proporciona 
    *password reset email: mensaje que contiene el correo recibido con el enlace
    *password reset confirm: proporciona el reestablecimiento, de contraseña una vez accedido al enlace
    *password reset complete: indica al usuario que la contraseña se reestablecio correctamente
"""

apps/proyecto/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, render_to_response, get_object_or_404

from apps.miembros.models import Miembro
from apps.sprint.models import Sprint
from .models import Proyecto
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .forms import UpadateForm
from django.urls import reverse_lazy

from apps.tipous.models import TipoUS, Actividad
from apps.us.models import US
from apps.proyecto.models import Proyecto

# Create your views here.
"""
funcion verifica_permisos de detalle:
* si el miembro esta autorizado se le 
da acceso ver el contenido del proyecto
* si no tiene esos permisos se le
 informa que no posee permisos

"""
@login_required()
def verifica_permiso_detalle(request,*args,**kwargs):
    has_permission = request.user.has_perm('proyecto.ver_proyecto')
    print("h proyecto detalle")
    print(has_permission)
    has_permission|= request.user.has_perm('proyecto.ver_proyecto', Proyecto.objects.get(id=kwargs['pk']))
    print(has_permission)
    if has_permission:
        return proyecto.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><p>No posee permisos</p></html>")

"""
funcion verifica_permisos de listar:
* si el miembro esta autorizado se le 
da acceso ver la lista de proyectos
* si no tiene esos permisos se le
 informa que no posee permisos

"""
@login_required()
def verifica_permiso_listar(request,*args,**kwargs):
    #has_permission = request.user.has_perm('proyecto.view_proyecto')
    print("h1")
   # print(has_permission)
    # has_permission|= request.user.has_perm('proyecto.view_proyecto', Proyecto.objects.get(id=kwargs['pk']))
    #if has_permission:
    print("entro")
    return proyectoList.as_view()(request, *args, **kwargs)
   # else:
    #    return HttpResponse("<html><p>No posee permisos</p></html>")

"""
funcion verifica_permisos de crear:
* si el miembro esta autorizado se le 
da acceso crear proyectos
* si no tiene esos permisos se le
 informa que no posee permisos

"""

@login_required()
def verifica_permiso_crear(request,*args,**kwargs):
    has_permission = request.user.has_perm('proyecto.add_proyecto')
   # has_permission|= request.user.has_perm('proyecto.change_proyecto', Proyecto.objects.get(id=kwargs['pk']))
    if has_permission:
        return RegistroProyecto.as_view()(request, *args, **kwargs)
    else:
       return HttpResponse("<html><p>No posee permisos</p></html>")

"""
funcion verifica_permisos de modificar:
* si el miembro esta autorizado se le 
da acceso a modificar atributos del proyecto
* si no tiene esos permisos se le
 informa que no posee permisos
"""

@login_required()
def verifica_permiso_modificar(request,*args,**kwargs):
    has_permission = request.user.has_perm('proyecto.modificar_proyecto')
    print("h proyecto modificar")
    print(has_permission)
    has_permission|= request.user.has_perm('proyecto.modificar_proyecto', Proyecto.objects.get(id=kwargs['pk']))
    print(has_permission)
    if has_permission:
        return ProyectoUpdate.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><p>No posee permisos</p></html>")

"""
funcion verifica_permisos de eliminar:
* si el miembro esta autorizado se le 
da acceso a eliminar proyecto
* si no tiene esos permisos se le
 informa que no posee permisos

"""

@login_required()
def verifica_permiso_eliminar(request, *args, **kwargs):
    has_permission = request.user.has_perm('proyecto.eliminar_proyecto')
    print("h proyecto eliminar")
    print(has_permission)
    has_permission |= request.user.has_perm('proyecto.eliminar_proyecto', Proyecto.objects.get(id=kwargs['pk']))
    print(has_permission)
    if has_permission:
        return ProyectoDelete.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><p>No posee permisos</p></html>")

"""
Clase Detalle de Proyecto el miembro que esta 
autorizado puede ver el detalle del proyecto 

ademas se modifican el metodo 
get_context_data para personalizar
la vista
"""
class proyecto(DetailView):
    model = Proyecto
    template_name = 'proyecto/index.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['proyecto'] = Proyecto.objects.get(id=self.kwargs['pk'])
        context['miembro'] = Miembro.objects.filter(proyecto=context['proyecto'])
        return context



"""
Clase Listar Proyecto el miembro que esta 
autorizado puede agregar miembros cada 
usuario puede ver los proyectos al
 cual pertenece

ademas se modifica el metodo get object
para personalizar la lista de proyectos

"""
class proyectoList(ListView):
    model = Proyecto
    template_name = 'proyecto/proyecto_list.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        queryset = queryset.filter(id=self.kwargs['ide'])
        obj = queryset.get()
        return obj

"""
Clase Listar Proyecto el usuario 
que tiene los permisos correspondiente 
puede registrar un nuevo proyecto

ademas se modifica el metodo form_valid
para personalizar la asignacion del 
usuario scrum master

"""

class RegistroProyecto(CreateView):
    model = Proyecto
    template_name = "proyecto/registrar.html"
    form_class = UpadateForm
    success_url = reverse_lazy('proyecto:listar')

    def form_valid(self, form):
        response = super(RegistroProyecto, self).form_valid(form)
        scrum=form.cleaned_data['scrum']
        usuario=User.objects.get(username=scrum)
        rolProyecto_ScrumMaster = Group.objects.get(name="Scrum Master")
        Miembro.objects.create(usuario=usuario, rolProyecto=rolProyecto_ScrumMaster, proyecto=self.object)
        return response


"""
Clase Actualizar Proyecto el miembro que esta 
autorizado puede modificar el proyecto
en al cual pertenece

"""

class ProyectoUpdate(UpdateView):
    model = Proyecto
    template_name = "proyecto/editar.html"
    form_class = UpadateForm
    success_url = reverse_lazy('proyecto:listar')


"""
Clase Eliminar Proyecto el miembro que esta 
autorizado puede eliminar proyecto

"""

class ProyectoDelete(DeleteView):
    model = Proyecto
    template_name = 'proyecto/proyecto_delete.html'
    success_url = reverse_lazy('proyecto:listar')

"""
funcion verifica_permisos de ver kanban:
* si el miembro esta autorizado se le 
da acceso ver el contenido del tablero
kanban
* si no tiene esos permisos se le
 informa que no posee permisos

"""
@login_required()
def ver_kanban(request, *args, **kwargs):
    has_permission = request.user.has_perm('proyecto.ver_kanban')
    print("h kanban ver")
    print(has_permission)
    has_permission |= request.user.has_perm('proyecto.consultar_sprint', Proyecto.objects.get(id=kwargs['pk']))
    print("h kanban consultar sprint")
    print(has_permission)
    if has_permission:
        return Kanban.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><p>No posee permisos</p></html>")

"""
Clase kanban el miembro que esta 
autorizado puede ver el tablero
kanban

ademas se modifica el metodo 
get_context_data para personalizar
los elementos para la vista

"""

class Kanban(DetailView):
    model = Proyecto
    template_name = "Tablero kanban/kanban.html"

    def get_context_data(self, **kwargs):
        """
        `Override:` personaliza los datos a visualizar en el tablero
        """
        context = super(Kanban,self).get_context_data(**kwargs)
        context['proyecto'] = Proyecto.objects.get(id=self.kwargs['pk'])
        sprint_list = Sprint.objects.filter(proyecto=context['proyecto'])
        context['sprint_list'] = sprint_list

        #user story dentro de un proyecto
        us_list = US.objects.filter(Q(proyecto=context["proyecto"]) & (Q(estado_us=1) | Q(estado_us=0) | Q(estado_us=2)))

        context['us_list'] = us_list
        #sprint_list = Sprint.objects.filter(proyecto=context['proyecto'])

        #cuenta la cantidad de us
        contador=us_list.count()

        #contiene la lista de todos los TUS temporal
        lista = TipoUS.objects.filter(proyecto=context['proyecto'])

        #contiene la lista de todos los TUS persistente
        tus_list = TipoUS.objects.filter(proyecto=context['proyecto'])

        #recorre los us y excluye de la lista TUS temporal todos los TUS que fueron asinados a los us
        for i in range(0,contador):
            lista=(lista.exclude(id=us_list[i].tipo_us.id))

        #recorre la lista de TUS temporal y de la lista de TUS persistente excluye dichos TUS temporales
        for i in lista:
            tus_list=(tus_list.exclude(id=i.id))

        print('tus_list')
        print(tus_list)

        context['tus_list'] = tus_list
        return context

"""
Clase Cambiar Fase el miembro que esta 
autorizado puede cambiar la fase en
la cual se encuentra un user story

ademas se modifica el metodo get succes
url para personalizar y mantener
en un estado valido a los us

"""
class CambiarFase_der(UpdateView):
    model = US
    fields = ['actividad_actual','estado_kanban']
    #template_name = "proyectos/ver_tablero.html"


    def get_success_url(self):
        # `Override:` personaliza la url de redireccion para casos de exito en la operacion.
        usid = self.kwargs["uid"]
        us = US.objects.get(id=usid)
        mayor = -1
        for fase in us.tipo_us.actividad_set.all():
            if fase.id > mayor:
                mayor = fase.id

        if(us.actividad_actual.id == mayor and us.estado_kanban == 2):
            us.estado_us = 2
            us.save()

        pr=self.kwargs['pk']
        return reverse_lazy("proyecto:kanban",kwargs = {'pk': pr})

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>

	<meta charset="UTF-8">

    <!-- css y js base-->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- icono de pagina sgp-->
    <link rel="shortcut icon" href= {% static 'icon/aa.png' %} />

    <!-- css y js para calendario-->
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    {% block extrajs %}
    {% endblock %}

	{% block extrastatic %}
	{% endblock %}

    <title> {% block title %} Sistema Gestor de Proyecto {% endblock %} </title>

<style type="text/css">
    {% block extraestilo %}
    {% endblock %}
</style>

</head>
<body>
    <div class="container" style="width: 100%">
    {% block navbar %}
        <div class="bs-docs-section clearfix">
            <div class="row">
                <div class="col-lg-12">
                    <div class="bs-component">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">

                                <!--Boton de ventana minimizada-->
                                <div class="navbar-header">
                                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Desplegable" >
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                     </button>
{#                                    <a class="fas fa-home navbar-brand" href="{% url 'usuario:index' %}"> Home</a>#}
                                    <a class="fas fa-home navbar-brand" href="{% url 'usuario:index' %}"> Home</a>
                                </div>

                                <!--Contenido del la barra navegador-->
                                <div class="collapse navbar-collapse" id="Desplegable">

                                    <!-- Menu dmae Usuarios: Listar, Registrar-->
                                    <ul class="nav navbar-nav">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Usuario <span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="{% url 'usuario:listar' %}">Lista de Usuario</a></li>
                                                <li><a href="{% url 'usuario:registrar' %}">Registrar Usuario</a></li>
                                            </ul>
                                        </li>
                                    <!-- Menu de Proyecto: Crear, Listar-->
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Proyecto<span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
{#                                                <li><a href="{% url 'proyecto:registrar' %}">Crear Proyecto</a></li>#}
                                                 <li><a href="{% url 'proyecto:listar' %} ">Lista de Proyecto</a></li>
                                            </ul>
                                        </li>

                                    <!-- Menu de Rol de Sistema: Listar, Registrar-->
{#                                    {% block habilitar_roles %}#}
{#                                        {% if perms.auth.add_group %}#}
                                            <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Roles<span class="caret"></span></a>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="{% url 'rol:listar' %}">Lista de Roles</a></li>
{#                                                    <li><a href="{% url 'rol:crear' %}">Registrar Rol</a></li>#}
                                                </ul>
                                            </li>
{#                                        {% endif %}#}
{#                                    {% endblock %}#}



                                    </ul>

                                    <!-- Menu opciones: Salir -->
                                    <ul class="nav navbar-nav navbar-right">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle far fa-user" data-toggle="dropdown" role="button" aria-expanded="false"> {{ request.user }}<span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="{% url 'logout' %}" style="display: inline;">Salir</a><i class="fas fa-sign-out-alt" style="display: inline;"></i></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}


        {% block content %}
        <h4>	Bloque de contenido		</h4>
        {% endblock %}


        {% block footer %}
        {% endblock%}
    </div>
</body>
</html>

templates/base/index.html
{% extends 'base/base.html' %}

{% block title %}Gestor de Proyectos{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <br/>
                <div class="list-group">
                    <a href="
                        {% if project %}
                            {% url 'proyecto:editar' project.id %}
                        {% endif %}" class="list-group-item list-group-item-action active"> Proyecto <button type="button" class="btn btn-primary fas fa-edit"></button></a>
                    <a href="#" class="list-group-item list-group-item-action"><b>Código: </b> {{ project.codigo }}</a>
                    <a href="#" class="list-group-item list-group-item-action"><b>Nombre: </b> {{ project.nombre }}.</a>
                    <a href="#" class="list-group-item list-group-item-action "><b>Estado: </b> {{ project.estado }}</a>
                    <a href="#" class="list-group-item list-group-item-action"><b>Descripcion: </b> {{ project.descripcion }} </a>
                    <a href="#" class="list-group-item list-group-item-action "><b>Fecha de Inicio: </b> {{ project.fechaInicio }}</a>
                    <a href="#" class="list-group-item list-group-item-action "><b>Fecha de Finalización: </b> {{ project.fechaFin }}</a>
                    <a href="#" class="list-group-item list-group-item-action "><b>Tiempo Restante: </b> {{ project.tiempoRestante }}</a>
                </div>
                <br/>
{#                <a href="productBacklog.html">#}
{#                    <button type="button" class="btn btn-info disabled">Product Backlog</button>#}
{#                </a>#}
{#                <a href="reportes.html">#}
{#                    <button type="button" class="btn btn-info" >Reportes</button>#}
{#                 </a>#}
                <br/><br/>
            </div>
            <div class="col-md-6" style="height: 500px">
{#                <h1 style="text-align: center"> Sprints </h1>#}
{#                <div class="card text-center">#}
{#                        <div class="card-header"> Sprint 4 </div>#}
{#                        <div class="card-body">#}
{#                        <p class="card-text">Total de U.S : xx . <a href="sprint.html" class="btn btn-primary">Ver</a> </p>#}
{#                        </div>#}
{#                        <div class="card-footer text-muted"> Restante 2 dias </div>#}
{#                </div>#}
{#                <h2 style="text-align: center"> sprints finalizados</h2>#}
{#                <div style="height: 45%;overflow-y: scroll">#}
{#                    <div class="card text-center">#}
{#                            <div class="card-header"> Sprint 1 </div>#}
{#                            <div class="card-body">#}
{#                            <p class="card-text">Total de U.S : xx . <a href="#" class="btn btn-primary">Ver</a> </p>#}
{#                            </div>#}
{#                            <div class="card-footer text-muted"> finalizado </div>#}
{#                    </div>#}
{#                    <br/>#}
{#                    <div class="card text-center">#}
{#                            <div class="card-header"> Sprint 2 </div>#}
{#                            <div class="card-body">#}
{#                            <p class="card-text">Total de U.S : xx . <a href="#" class="btn btn-primary">Ver</a> </p>#}
{#                            </div>#}
{#                            <div class="card-footer text-muted"> finalizado </div>#}
{#                    </div>#}
{#                    <br/>#}
{#                    <div class="card text-center">#}
{#                            <div class="card-header"> Sprint 3 </div>#}
{#                            <div class="card-body">#}
{#                            <p class="card-text">Total de U.S : xx . <a href="#" class="btn btn-primary">Ver</a> </p>#}
{#                            </div>#}
{#                            <div class="card-footer text-muted"> finalizado </div>#}
{#                    </div>#}
{#                </div>#}
            </div>
            <div class="col-md-3 ">
                <br/>
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active"> Miembros </a>
                    {% for m in miembro %}
                        <a href="../proyecto/{{ project.id }}/miembro/modificar/{{m.id}}" class="list-group-item list-group-item-action">
                            {{m.usuario.first_name}} {{m.usuario.last_name}}
                            <button type="button" class="fas fa-edit"></button>
                        </a>
                    {% endfor %}
                </div>
                <br/><br/>
            </div>
        </div>
    </div>
{% endblock %}