apps/proyecto/urls.py
from django.urls import include, re_path
from django.conf.urls import url
from .views import verifica_permiso_listar, verifica_permiso_detalle, verifica_permiso_modificar, \
    verifica_permiso_eliminar, verifica_permiso_crear, ver_kanban, CambiarFase_der,verifica_permiso_cabiarUsuario,CambiarEstado,\
    finalizar_us,listarUSfinalizados
#from .views import proyecto, verifica_permiso_detalle, proyectoList, \
#   ProyectoUpdate, ProyectoDelete, ver_kanban, RegistroProyecto, verifica_permiso_listar
app_name = 'proyecto'

urlpatterns = [
    re_path(r'^listar/', verifica_permiso_listar, name='listar'),
    re_path(r'^registrar/', verifica_permiso_crear, name="registrar"),
    re_path(r'^(?P<pk>\d+)/detalle/$', verifica_permiso_detalle , name='index'),
    re_path(r'^editar/(?P<pk>\d+)$', verifica_permiso_modificar, name='editar'),
    re_path(r'^eliminar/(?P<pk>\d+)$', verifica_permiso_eliminar, name='eliminar'),

    url(r'^(?P<pk>\d+)/rolProyecto/', include('apps.rolDeProyecto.urls', namespace='rolProyecto')),
    url(r'^(?P<pk>\d+)/miembro/', include('apps.miembros.urls', namespace='miembro')),
    url(r'^(?P<pk>\d+)/us/', include('apps.us.url', namespace='us')),
    url(r'^(?P<pk>\d+)/tablero_Kanban/$', ver_kanban, name="kanban"),
    url(r'^(?P<pk>\d+)/tablero_Kanban/cambiar_usuario/(?P<tmid>\d+)$', verifica_permiso_cabiarUsuario, name="cambiarUsuario"),
    url(r'^(?P<pk>\d+)/sprint/', include('apps.sprint.urls', namespace='sprint')),
    url(r'^(?P<pk>\d+)/tipous/', include('apps.tipous.urls', namespace='tus')),

    url(r"^(?P<pk>\d+)/tablero/cambiar_fase/(?P<uid>\d+)$", CambiarFase_der.as_view(), name="cambiar_fase"),
    url(r"^(?P<pk>\d+)/cambiar_estado/", CambiarEstado.as_view(), name="cambiar_estado"),
    url(r"^(?P<pk>\d+)/finalizar_user_story/(?P<tmid>\d+)$", finalizar_us.as_view(), name="finalizar_us"),
    url(r"^(?P<pk>\d+)/Release_Backlog/$", listarUSfinalizados.as_view(), name="release_backlog"),
]

"""
urlpatterns = [
    re_path(r'listar/', verifica_permiso_listar, name='listar'),
    re_path(r'^registrar/', RegistroProyecto.as_view(), name="registrar"),
    re_path(r'^(?P<pk>\d+)/detalle/$', verifica_permiso_detalle , name='index'),
    re_path(r'^editar/(?P<pk>\d+)$', ProyectoUpdate.as_view(), name='editar'),
    re_path(r'^eliminar/(?P<pk>\d+)$', ProyectoDelete.as_view(), name='eliminar'),

    url(r'^(?P<pk>\d+)/rolProyecto/', include('apps.rolDeProyecto.urls', namespace='rolProyecto')),
    url(r'^(?P<pk>\d+)/miembro/', include('apps.miembros.urls', namespace='miembro')),
    url(r'^(?P<pk>\d+)/us/', include('apps.us.url', namespace='us')),
    url(r'^(?P<pk>\d+)/tablero Kanban/$', ver_kanban, name="kanban"),
    url(r'^(?P<pk>\d+)/sprint/', include('apps.sprint.urls', namespace='sprint')),
    url(r'^(?P<pk>\d+)/tus/', include('apps.tipous.urls', namespace='tus')),
]
"""

project01/urls.py
"""project01 URL Configuration

La lista `urlpatterns` enruta las URL a las vistas. Para más información por favor vea:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Ejemplos:
Vistas de funciones
    1. Agregar una importación: desde las vistas de importación my_app
    2. Agregue una URL a urlpatterns: ruta ('', views.home, name = 'home')
Vistas basadas en clase
    1. Agregue una importación: desde other_app.views import Inicio
    2. Agregue una URL a urlpatterns: path ('', Home.as_view (), name = 'home')
Incluyendo otro URLconf
    1. Importe la función include (): desde django.urls import include, path
    2. Agregue una URL a urlpatterns: ruta ('blog /', include ('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from project01.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name = 'index'),
    path('usuario/',include('apps.usuario.urls',namespace='usuario')),
    path('us/',include('apps.us.url',namespace='us')),
    path('rol/', include(('apps.rol.urls','rol'), namespace='rol')),
    path('proyecto/', include('apps.proyecto.urls', namespace='proyecto')),


    path('',LoginView.as_view(),{'template_name':'templates/registration/login.html'}, name='login'),
    path('logout/',logout_then_login, name='logout'),
    url(r'^reset/password_reset',PasswordResetView.as_view(),{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    path('reset/password_reset_done',PasswordResetDoneView.as_view(),{'template_name':'registration/password_reset_done'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',PasswordResetConfirmView.as_view(),{'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'reset/done',PasswordResetCompleteView.as_view(),{'template_name':'registration/password_reset_complete.html'},name='password_reset_complete'),
]

""""
    se tienen las direcciones de:
    -usuario
    -rol
    -Login
    -Recuperacion de contraseña que consta de:
    
    *password reset done: envia un correo, con un enlace para reestablecer la contraseña, al correo que el usuario proporciona 
    *password reset email: mensaje que contiene el correo recibido con el enlace
    *password reset confirm: proporciona el reestablecimiento, de contraseña una vez accedido al enlace
    *password reset complete: indica al usuario que la contraseña se reestablecio correctamente
"""

apps/us/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from apps.proyecto.models import Proyecto
from apps.tipous.models import TipoUS, Actividad
from apps.miembros.models import Miembro

estados_kanban = ((0,'To do'),(1,'Doing'),(2,'Done'))
estados_us = ((0,'En espera'), (1,'En ejecucion'), (2, 'Control de calidad'), (3, 'Finalizado'), (4, 'Cancelado'))

class US(models.Model):
    """
    Clase UserStory:
    Registra un nombre, una descripcion corta,
    una descriocion larga, una prioridad,
    una fase, un estado, una fecha de modificacion,
    un valor de negocio y tecnico, un archivo adjunto,
    un tiempo estimado y dedicado para el user story y
    lo asocia a un proyecto, a un tipo de user story
    y desarrolador.
    """
    nombre = models.CharField(max_length=100, unique=True)
    descripcion_corta = models.CharField(max_length=100)
    descripcion_larga = models.TextField()
    prioridad = models.IntegerField(choices=((i, i) for i in range(1, 11)), default=1)
    prioridad_final = models.IntegerField(default=0)
    actividad_actual = models.ForeignKey(Actividad, on_delete=models.SET_NULL, null=True)
    estado_kanban = models.IntegerField(choices=estados_kanban, default=0)
    estado_us = models.IntegerField(choices=estados_us, default=0)
    tipo_us = models.ForeignKey(TipoUS, on_delete=models.SET_NULL, null=True)
    proyecto = models.ForeignKey(Proyecto, null=True,blank=True,on_delete=models.CASCADE)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    valor_negocio = models.PositiveIntegerField(validators=[MaxValueValidator(10)])
    valor_tecnico = models.PositiveIntegerField(validators=[MaxValueValidator(10)])
    archivo_adjunto = models.FileField(default=None, blank=True)
    # historial =
    tiempo_estimado = models.IntegerField(default=3)
    tiempo_dedicado = models.IntegerField(default=0)
    team_member = models.ForeignKey(Miembro, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        """
        Meta-Clase:
        Establece los parametros de ordenamiento
         de los objetos de la clase.
        """
        ordering = ['-prioridad_final', "nombre"]

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        old = US.objects.filter(id=self.id)
        #si hay objeto en el US
        #if old.count() > 0:
        #Calcula la prioridad final mediante la formula dada en la ERS
        self.prioridad_final = (2*self.valor_negocio+self.prioridad+2*self.valor_tecnico)/5
        #Si el tiempo dedicado excede al tiempo estimado se prioriza el US dandole un valor grande
        #falta mas condiciones
        if self.tiempo_dedicado > self.tiempo_estimado:
            self.prioridad_final = 12

        super().save(force_insert=force_insert,
                     force_update=force_update,
                     using=using,
                     update_fields=update_fields)
    """
    **__str__** retorna una cadena que representa el nombre del user story del proyecto en cuestion
    """

    def __str__(self):
        return self.nombre

apps/proyecto/forms.py
from django.contrib.auth.models import User

from .models import Proyecto
from django import forms


"""
    Formulario de Actualizacion:
    se extiende de la calse forms.ModelsForm
    
    la seleccion de los estados posibles del Proyecto:
    Pendiente, Activo, Cancelado
    
    En la Clase Meta se da la posibilidad de modificar
    los siguientes campos:
    'codigo',
    'nombre',
    'descripcion',
    'fechaInicio',
    'fechaFin',
    'estado',
"""


class UpadateForm(forms.ModelForm):
    # estado = forms.ChoiceField(choices=(('pendiente','pendiente'),('activo','activo'),('cancelado','cancelado')))
    scrum = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True,is_superuser=False).exclude(username='AnonymousUser'))

    class Meta:
        model = Proyecto
        fields = [
                'codigo',
                'nombre',
                'descripcion',
                'fechaInicio',
                'fechaFin',
                # 'estado',
                'scrum'
                ]
        labels = {
                'codigo': 'Codigo',
                'nombre': 'Nombre',
                'descripcion': 'Descripcion',
                'fechaInicio': 'FechaInicio',
                'fechaFin': 'FechaFin',
                # 'estado' : 'Estado',
                'scrum': 'Scrum Master'
                }

        widgets= {
            'fechaInicio' : forms.DateTimeInput(attrs= {'class': 'datetime-input'}),
            'fechaFin': forms.DateTimeInput(attrs= {'class': 'datetime-input'}),
            }

#
# class RegistroForm(forms.ModelForm):
#
#     class Meta:
#         model = Proyecto
# #         fields = [{ 'fechaFin': 'FechaFin', }]
# #
# #         # widgets= {
# #         #     # 'codigo' : forms.NumberInput(),
# #         #     # 'nombre': forms.(),
# #         #     # 'descripcion': forms.TimeField(),
# #         #     'fechaInicio' : forms.DateTimeInput(attrs= {'class': 'datetime-input'}),
# #         #     'fechaFin': forms.DateTimeInput(attrs= {'class': 'datetime-input'}),
# #         #     'username': forms.TextInput(attrs={'class':'form-control'}),
# #         #     'first_name': forms.TextInput(attrs={'class':'form-control'}),
# #         #     'last_name': forms.TextInput(attrs={'class':'form-control'}),
# #         #     #'email': forms.EmailField(attrs={'class':'form-control'}),
# #         # }

apps/nota/views.py
from django.shortcuts import get_object_or_404

from apps.proyecto.models import Proyecto

from apps.nota.models import NotaUs
from apps.nota.forms import FormNotas
from apps.us.models import US
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import ListView
"""
el usuario encargado
de mantener el user story carga
los datos de la nota como nombre
descripcion, horas trabajadas, y
archivo adjunto
"""
class notaUS(CreateView):
   model = NotaUs
   form_class = FormNotas
   template_name = 'us/crear_notas.html'
   def get_context_data(self, **kwargs):
      """
      `Override:` genera una lista personalizada
      de los user story en base al proyecto,
        A fin de visualizar dichos datos en el menu.
      """
      context = super(CreateView, self).get_context_data(**kwargs)
      context['proyecto'] = Proyecto.objects.get(id=self.kwargs.get('pk'))
      context['us'] = US.objects.get(id=self.kwargs.get('tmid'))
      return context

   def form_valid(self, form):
       nota =form.save(commit= False)
       us= US.objects.get(pk = self.kwargs.get('tmid'))
       nota.us = us
       nota.us.tiempo_dedicado = nota.us.tiempo_dedicado + nota.horas
       nota.us.save()
       return super().form_valid(form)

   def get_success_url(self):
       # `Override:` personaliza la url de redireccion para casos de exito en la operacion.
       l = self.object.us.proyecto.id
       k = self.object.us.id
       return reverse_lazy('proyecto:us:detalle_us', kwargs={'pk':l ,'tmid': k} )

"""
Clase Lista de notas:
Genera una lista de todas
las notas que fueron almacenadas
en el us
"""
class notaList(ListView):
   model = NotaUs
   template_name = 'us/listar_nota.html'

   def get_queryset(self):
       """
       `Override:` personaliza la lista de user stories
       a fin de proyectar solo los  pertenecientes al proyecto.
       """
       self.us = get_object_or_404(US, id=self.kwargs.get('tmid'))
       return NotaUs.objects.filter(us=self.us)

   def get_context_data(self, **kwargs):
       """
       `Override:` agrega mas informacion para complementar los datos del menu.
       """
       context = super(ListView, self).get_context_data(**kwargs)
       context['proyecto'] = Proyecto.objects.get(id=self.kwargs.get('pk'))
       context['us'] = US.objects.get(id=self.kwargs.get('tmid'))
       return context

templates/proyecto/ProductBacklog.html
{% extends 'base/proyecto.html' %}

{% block title %}
    Product Backlog
{% endblock %}

{% block content %}
    {% load guardian_tags %}
    {% get_obj_perms request.user for proyecto as "US_perms" %}
    <div class="container-fluid">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h1>
                    <p class="text-center">{{ proyecto.nombre }} : Product Backlog</p>
                </h1>
            </div>
            <div class="panel-body">
                <p></p>
                <a class= "btn btn-primary" href="/proyecto/{{ proyecto.id }}/detalle">Volver al proyecto</a>
            <!--
                <p align="right">
                    {# if proyecto.estado != "Proyecto Cancelado" and proyecto.estado != "Finalizado" #}
                    <a class="btn btn-success" href="/proyecto/{#{ proyecto.id }#}/userstory/crear_us">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </a>
                     {#  endif #}
                </p>-->
                <table class="table table-bordered">
                    <div><p> </p></div>
                    {% if us_list %}
                    <thead>
                        <tr>
                            <td><b><center>N°</center></b></td>
                            <td><b><center>Id</center></b></td>
                            <td><b><center>Nombre</center></b></td>
                            <td><b><center>Descripción</center></b></td>
                            <td><b><center>Tipo US</center></b></td>
                            <td><b><center>Actividad</center></b></td>
                            <td><b><center>Estado</center></b></td>
                            <td><b><center>Prioridad</center></b></td>
                            <td><b><center>Asignado a:</center></b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <div></div>
                            {% for us in us_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ us.id }}</td>
                                    <td>{{ us.nombre }}</td>
                                    <td>{{ us.descripcion_corta }}</td>
                                    <td>{{ us.tipo_us }}</td>
                                    <td><center>{{ us.actividad_actual }}</center></td>
                                    <td><center>{{ us.get_estado_kanban_display }}</center></td>
                                    <td><center>{{ us.prioridad_final }}</center></td>
                                    {% if us.team_member.id == null %}
                                        <td style="color:#ff7b08" ;><i>Aún no ha sido asignado a algún integrante</i></td>
                                    {% else %}
                                        <td>{{ us.team_member.usuario.username }}</td>
                                    {% endif %}
                                    <td><center>
                                        {#  if "view_us" in US_perms #}
                                            <a class="btn btn-default" href="/proyecto/{{ proyecto.id }}/us/detalle_us/{{ us.id }}">Ver más</a>
                                        {# endif #}
                                    </center></td>
                                </tr>
                            {% endfor %}
                    </tbody>
                    {% else%}
                        <h2>No hay registros de User Stories</h2>
                    {% endif %}
                </table>
                <ul class="pagination">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                         <a class="page-link" aria-label="Anterior" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if page_obj.has_next %}
                         <a class="page-link" aria-label="Siguiente" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/proyecto/cambiar_Usuario.html
{% extends 'base/proyecto.html' %}
{% block title %}
    kanban | Modificar usuario asignado a {{ user_story }}
{% endblock %}
{% block content %}
 <form method="post">
  {% csrf_token %}
            <h1 align="center">User story : {{ user_story }} </h1>
        <div class="row">
        <div class="col-md-8 col-md-offset-1">
                <div class="form-group">
                    <tr>
                    <th><label style="width: 140px;">Usuario asignado:</label></th>
                    <td><input style="width: 200px;" class="col-md-offset-1"  value='{{usuario_actual}}'></td>
                    </tr>
                </div>
            </div>

        <div class="col-md-8 col-md-offset-1">
            <tr>
                <th><label for="id_team_member" style="min-height: 100px">Miembros del Sprint:</label></th>
                <td>
                    <select name="team_member" id="id_team_member" style="width: 200px;" class="col-md-offset-1" required>
                        <option value="" selected> </option>
                    {% for usuarios in miembro_list %}
                        <option value="{{ usuarios.id}}">
                            {{usuarios.usuario}}
                        </option>
                    {% endfor %}
                    </select>
                 </td>
            </tr>
        </div>
        </div>
         <div class="row">
            <div class="col-md-8 col-md-offset-1">
                <div class="form-group">
                    <a class= "btn btn-danger" href={% url 'proyecto:kanban' proyecto.id%}>Cancelar</a>
                    <button class="btn btn-primary" type="submit">Guardar</button>
                </div>
            </div>
         </div>

 </form>

{%  endblock%}

templates/proyecto/editar.html
{% extends 'base/base.html'%}

{% block content%}
<form method = "post">
	{%csrf_token%}
    <div class="input-group">
        {{form.as_p}}
    </div>
    </div>
{#	<button type="submit"> Guardar </button>#}
	<button class="btn btn-primary" type="submit"> Guardar </button>
    <a class="btn btn-default" href="{% url 'proyecto:listar' %}">Cancelar</a>
</form>
<script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format : 'DD/MM/YYYY HH:mm:ss',
        });
    });
</script>
{% endblock %}

templates/proyecto/finalizar_us.html
{% extends 'base/proyecto.html' %}

{% block title %}
    Finalizar User Story
{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
    <div class="container center-block">
        <p> </p>
        <h3>Confirmacion de Finalizacion</h3>
	    <h4>&nbsp;¿Desea Finalizar el user story ?</h4>
	    <button class="btn btn-danger" type="submit">Finalizar</button>
        <a class="btn btn-default" href="/proyecto/{{ proyecto.id }}/kanban">Cancelar</a>
    </div>
</form>
{% endblock %}

templates/proyecto/index.html
{% extends 'base/proyecto.html' %}

{% block title %}Gestor de Proyectos{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <br/>
                <div class="list-group">
                    <a href="{% url 'proyecto:editar' proyecto.id %}" class="list-group-item list-group-item-action active"> Proyecto <button type="button" class="btn btn-primary fas fa-edit"></button></a>
                    <a href="#" class="list-group-item list-group-item-action"><b>Código: </b> {{ proyecto.codigo }}</a>
                    <a href="#" class="list-group-item list-group-item-action"><b>Nombre: </b> {{ proyecto.nombre }}.</a>
                    <a href="#" class="list-group-item list-group-item-action "><b>Estado: </b> {{ proyecto.estado }}</a>
                    <a href="#" class="list-group-item list-group-item-action"><b>Descripcion: </b> {{ proyecto.descripcion }} </a>
                    <a href="#" class="list-group-item list-group-item-action "><b>Fecha de Inicio: </b> {{ proyecto.fechaInicio }}</a>
                    <a href="#" class="list-group-item list-group-item-action "><b>Fecha de Finalización: </b> {{ proyecto.fechaFin }}</a>
                    <a href="#" class="list-group-item list-group-item-action "><b>Tiempo Restante: </b> {{ proyecto.tiempoRestante }}</a>
                </div>
                <br/>
                {% if proyecto.estado == "Pendiente" %}
                    <form method="post" action={% url "proyecto:cambiar_estado" proyecto.id%}>
                        {% csrf_token %}
                        <input hidden name="estado" value="activo">
                        <button type="submit" class="btn btn-info ">Iniciar Proyecto</button>
                    </form>
                {% endif %}
                {% if proyecto.estado == "activo" %}
                    <form method="post" action={% url "proyecto:cambiar_estado" proyecto.id%}>
                        {% csrf_token %}
                        <input hidden name="estado" value="cancelado">
                        <button type="submit" class="btn btn-info" >Cancelar Proyecto</button>
                    </form>
                {% endif %}
                <br/><br/>
            </div>
            <div class="col-md-6" style="height: 500px">
{#                <h1 style="text-align: center"> Sprints </h1>#}
{#                <div class="card text-center">#}
{#                        <div class="card-header"> Sprint 4 </div>#}
{#                        <div class="card-body">#}
{#                        <p class="card-text">Total de U.S : xx . <a href="sprint.html" class="btn btn-primary">Ver</a> </p>#}
{#                        </div>#}
{#                        <div class="card-footer text-muted"> Restante 2 dias </div>#}
{#                </div>#}
{#                <h2 style="text-align: center"> sprints finalizados</h2>#}
{#                <div style="height: 45%;overflow-y: scroll">#}
{#                    <div class="card text-center">#}
{#                            <div class="card-header"> Sprint 1 </div>#}
{#                            <div class="card-body">#}
{#                            <p class="card-text">Total de U.S : xx . <a href="#" class="btn btn-primary">Ver</a> </p>#}
{#                            </div>#}
{#                            <div class="card-footer text-muted"> finalizado </div>#}
{#                    </div>#}
{#                    <br/>#}
{#                    <div class="card text-center">#}
{#                            <div class="card-header"> Sprint 2 </div>#}
{#                            <div class="card-body">#}
{#                            <p class="card-text">Total de U.S : xx . <a href="#" class="btn btn-primary">Ver</a> </p>#}
{#                            </div>#}
{#                            <div class="card-footer text-muted"> finalizado </div>#}
{#                    </div>#}
{#                    <br/>#}
{#                    <div class="card text-center">#}
{#                            <div class="card-header"> Sprint 3 </div>#}
{#                            <div class="card-body">#}
{#                            <p class="card-text">Total de U.S : xx . <a href="#" class="btn btn-primary">Ver</a> </p>#}
{#                            </div>#}
{#                            <div class="card-footer text-muted"> finalizado </div>#}
{#                    </div>#}
{#                </div>#}
            </div>
            <div class="col-md-3 ">
                <br/>
                <div class="list-group">
                    <a href="{% url 'proyecto:miembro:listar' proyecto.id%}" class="list-group-item list-group-item-action active"> Miembros </a>
                    {% for m in miembro %}
                        <a href="{% url 'proyecto:miembro:modificar' proyecto.id m.id%}" class="list-group-item list-group-item-action">
                            {{m.usuario.first_name}} {{m.usuario.last_name}} ({{ m.usuario.username  }} )
                            <button type="button" class="fas fa-edit"></button>
                        </a>
                    {% endfor %}
                </div>
                <br/><br/>
            </div>
        </div>
    </div>
{% endblock %}

templates/proyecto/proyecto_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea Eliminar el registro de {{ object.nombre }}? </h3>
    <button class="btn btn-danger" type="submit">Si, eliminar </button>
    <a class="btn btn-default" href="{% url 'proyecto:listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/proyecto/proyecto_list.html
{% extends 'base/base.html' %}
{% block title %}Lista de Proyectos{% endblock %}
{% block content %}
<div class="table-responsive" style="max-height: 70vh; overflow-y: scroll;">
    <table class="table table-bordered">
        <theard>
            <tr>
                <td>Codigo</td>
                <td>Nombre</td>
                <td>TiempoRestante</td>
                <td>Estado</td>
                <td>Opciones</td>
            </tr>
        </theard>
        <tbody>
            {% if object_list %}
                    {% for proyecto in object_list %}
                    <tr>
                        <td>{{proyecto.codigo }}</td>
                        <td>{{proyecto.nombre }}</td>
                        <td>{{proyecto.tiempoRestante}}</td>
                        <td>{{proyecto.estado}}</td>
                        <td>
                            <a class="btn btn-default" href="{% url 'proyecto:index' proyecto.id %}">Detalle</a>
                            <a class="btn btn-primary" href="{%  url 'proyecto:editar' proyecto.id %}"> Editar</a>
                            <a class="btn btn-danger" href="{% url 'proyecto:eliminar' proyecto.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {%endfor%}
            {% else %}
                <h1> No hay registros de proyectos </h1>
            {% endif %}
        </tbody>
    </table>
</div>
<a class="btn btn-primary" href="{% url 'proyecto:registrar' %}">Crear Proyecto</a>
{% endblock%}

templates/proyecto/registrar.html
{% extends 'base/base.html'%}

{% block content%}
<form method = "post">
	{%csrf_token%}
    <div class="input-group">
       {{form.as_p}}
    </div>
	<button class="btn btn-primary" type="submit"> Guardar </button>
    <a class="btn btn-default" href="{% url 'proyecto:listar' %}">Cancelar</a>
</form>
    <script>
     $(function () {
         $('.datetime-input').datetimepicker({
             format : 'DD/MM/YYYY HH:mm:ss',
         });
     });
    </script>
{% endblock %}