apps/miembros/urls.py
from django.conf.urls import url
from django.urls import path

from apps.miembros.views import verifica_permiso_listar, verifica_permiso_agregar, verifica_permiso_modificar, verifica_permiso_eliminar, ver_productBacklog


app_name = 'miembro'


urlpatterns = [
    path('', verifica_permiso_listar, name='listar'),
    url(r'^agregar$', verifica_permiso_agregar, name='agregar'),
    url(r'^modificar/(?P<id_>\d+)$', verifica_permiso_modificar, name='modificar'),
    url(r'^eliminar/(?P<ide>\d+)/$', verifica_permiso_eliminar, name='eliminar'),
   # url(r'^eliminar/(?P<ide>\d+)', EliminarMiembro.as_view(), name='eliminar'),

    url(r'^Product Backlog/$', ver_productBacklog, name='productBacklog'),
]

project01/urls.py
"""project01 URL Configuration

La lista `urlpatterns` enruta las URL a las vistas. Para más información por favor vea:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Ejemplos:
Vistas de funciones
    1. Agregar una importación: desde las vistas de importación my_app
    2. Agregue una URL a urlpatterns: ruta ('', views.home, name = 'home')
Vistas basadas en clase
    1. Agregue una importación: desde other_app.views import Inicio
    2. Agregue una URL a urlpatterns: path ('', Home.as_view (), name = 'home')
Incluyendo otro URLconf
    1. Importe la función include (): desde django.urls import include, path
    2. Agregue una URL a urlpatterns: ruta ('blog /', include ('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from project01.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name = 'index'),
    path('usuario/',include('apps.usuario.urls',namespace='usuario')),
    path('us/',include('apps.us.url',namespace='us')),
    path('rol/', include(('apps.rol.urls','rol'), namespace='rol')),
    path('proyecto/', include('apps.proyecto.urls', namespace='proyecto')),


    path('',LoginView.as_view(),{'template_name':'templates/registration/login.html'}, name='login'),
    path('logout/',logout_then_login, name='logout'),
    url(r'^reset/password_reset',PasswordResetView.as_view(),{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    path('reset/password_reset_done',PasswordResetDoneView.as_view(),{'template_name':'registration/password_reset_done'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',PasswordResetConfirmView.as_view(),{'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'reset/done',PasswordResetCompleteView.as_view(),{'template_name':'registration/password_reset_complete.html'},name='password_reset_complete'),
]

""""
    se tienen las direcciones de:
    -usuario
    -rol
    -Login
    -Recuperacion de contraseña que consta de:
    
    *password reset done: envia un correo, con un enlace para reestablecer la contraseña, al correo que el usuario proporciona 
    *password reset email: mensaje que contiene el correo recibido con el enlace
    *password reset confirm: proporciona el reestablecimiento, de contraseña una vez accedido al enlace
    *password reset complete: indica al usuario que la contraseña se reestablecio correctamente
"""

apps/miembros/models.py
from django.contrib.auth.models import User, Permission, Group
from django.db import models
from guardian.shortcuts import get_perms, remove_perm, assign_perm

#from apps.rolDeProyecto.models import RolDeProyecto
from apps.proyecto.models import Proyecto

"""
Se crea el Modelo Miembro, en el se guardan 
los datos del un miembro de Proyecto
usuario: como el id foraneo de usuario, 
proyecto: el proyecto al cual pertenece,
rolProyecto: el rol en el proyecto,
horasDeTrabajo: las horas de trabajo realiza 
"""

"""
Se modifica la funcion save para operaciones 
de creacion, actualizacion de datos
"""

"""
Se modifica la funcion de delete para eliminar
el permiso del miembro en el proyecto
y dejar en un estado valido
"""


class Miembro(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    rolProyecto = models.ForeignKey(Group, on_delete=models.SET_NULL,null=True)
    horasDeTrabajo = models.PositiveIntegerField(default=1)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        print(" esto es en save .self:"+str(self))
        old = Miembro.objects.filter(id=self.id)
        if old.count() > 0:
            print("old count >0")
            print(old.count())
            for x in get_perms(self.usuario, self.proyecto):
                print("Remover " + x + " a " + self.usuario.username + " en " + self.proyecto.nombre)
                remove_perm(x, self.usuario, self.proyecto)
        super().save(force_insert=force_insert,
                     force_update=force_update,
                     using=using,
                     update_fields=update_fields)
        rolenProyecto = self.rolProyecto
        print("self")
        print(self.rolProyecto)
        print("rol")
        print(rolenProyecto)
        if rolenProyecto == None:
            print("entro en none de rol")
            x = Permission.objects.get(codename="view_proyecto")
            print("Otorgar " + x.codename + " a " + self.usuario.username + " en " + self.proyecto.nombre)
            assign_perm(x.codename, self.usuario, self.proyecto)
        else:
            print("entro el else")
            print("rol en proyecto permissions all")
            print(rolenProyecto.permissions.all())
            for x in rolenProyecto.permissions.all():
                print("El valor de x")
                print(x)
                if x.content_type.name == 'permiso':
                    print("Otorgar " + x.codename + " a " + self.usuario.username + " en " + self.proyecto.nombre)
                    assign_perm(x.codename, self.usuario, self.proyecto)
                    print("asigno a usuario" + x.codename)
                    var = self.usuario.has_perm(x.codename,self.proyecto.nombre)
                    print(var)

    def delete(self, *args, **kwargs):
        print("llego a delete del modelo")
        old = Miembro.objects.filter(id=self.id)
        if old.count() > 0:
            for x in get_perms(self.usuario, self.proyecto):
                print("Remover " + x + " a " + self.usuario.username + " en " + self.proyecto.nombre)
                remove_perm(x, self.usuario, self.proyecto)
        super().delete(*args, **kwargs)

    def __str__(self):
        try:
            usuario=self.usuario.username
        except:
            usuario=""
        try:
            rol_asignado=self.rolProyecto.name
        except:
            rol_asignado="?"
        try:
            proyecto_in=self.proyecto.nombre
        except:
            proyecto_in=""

        return "%s" %(usuario)

    class Meta:
            unique_together = (('usuario', 'proyecto'),)
            ordering = ["id","rolProyecto","proyecto", "usuario"]

apps/miembros/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User, Group
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from apps.miembros.models import Miembro
from apps.proyecto.models import Proyecto
from apps.us.models import US
from django.contrib.auth.mixins import PermissionRequiredMixin


"""
funcion verifica_permisos de agregar:
* si el miembro esta autorizado se le 
da acceso agregar miembros del proyecto
* si no tiene esos permisos se le
 informa que no posee permisos

"""


@login_required()
def verifica_permiso_agregar(request,*args,**kwargs):
    if has_perm(request.user, 'proyecto.agregar_miembro_proyecto', kwargs['pk']):
        print("tiene permiso agregar miembro")
        return AgregarMiembro.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><h1><p>No posee permisos</p></h1></html>")

""""
funcion verifica_permisos de listar:
* si el miembro esta autorizado se le da 
acceso para ver la lista de miembros del Proyecto
* si no tiene esos permisos se le 
informa que no posee permisos
"""


@login_required()
def verifica_permiso_listar(request, *args, **kwargs):
    if has_perm(request.user, 'proyecto.verlista_miembro_proyecto', kwargs['pk']):
        print("tiene permiso ver lista miembro")
        return ListarMiembro.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><h1><p>No posee permisos</p></h1></html>")


"""
funcion verifica_permisos de modificar:
* si el miembro esta autorizado se le da 
acceso modificar miembros del proyecto
* si no tiene esos permisos se le
 informa que no posee permisos
"""


@login_required()
def verifica_permiso_modificar(request, *args, **kwargs):
    proy_id = str(Miembro.objects.get(id=kwargs['id_']).proyecto_id)
    if proy_id != kwargs['pk']:
        kwargs['pk'] = proy_id
        return redirect("miembro:modificar", *args, **kwargs)
    if has_perm(request.user, 'proyecto.modificar_miembro_proyecto', kwargs['pk']):
        print("tiene permiso modificar miembro")
        return ModificarMiembro.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><h1><p>No posee permisos</p></h1></html>")

"""
funcion verifica_permisos de eliminar:
* si el miembro esta autorizado se le da
 acceso eliminar miembros del proyecto
* si no tiene esos permisos se le informa 
que no posee permisos
"""


@login_required()
def verifica_permiso_eliminar(request, *args, **kwargs):
    proy_id = str(Miembro.objects.get(id=kwargs['ide']).proyecto_id)

    if proy_id != kwargs['pk']:
        kwargs['pk'] = proy_id
        return redirect("proyecto:miembro:eliminar", *args, **kwargs)
    if has_perm(request.user, 'proyecto.eliminar_miembro_proyecto', kwargs['pk']):
        print("tiene permiso eliminar miembro")
        return EliminarMiembro.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><h1><p>No posee permisos</p></h1></html>")


"""
Clase Agregar Miembro el miembro que esta 
autorizado puede agregar miembros en el cual 
especifica el usuario, el rol que posee 
en el proyecto, las horas que trabaja

ademas se modifican los metodos post, 
get_context_data y get_success_url
para personalizar y mantener los datos 
en estado correcto

"""


class AgregarMiembro(CreateView):
    model = Miembro
    fields = ['usuario', 'rolProyecto', 'horasDeTrabajo']
    template_name = "miembro/Añandir_miembro.html"


    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        form.instance.proyecto = Proyecto.objects.get(id=kwargs['pk'])
        if form.is_valid():
            return self.form_valid(form)
        else:
            print(False)
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        #sobreescibe el contexto
        context = super(CreateView, self).get_context_data(**kwargs)
        #crea el contexto proyecto con la id de proyecto actual
        context['proyecto'] = Proyecto.objects.get(id=self.kwargs['pk'])
        #Crea la lista de Miembros que pertenece al proyecto
        miembrosLista = Miembro.objects.filter(proyecto=context['proyecto'])
        #Crea una lista de usuarios del sistema que estan activos y no son superusuarios
        usuariosLista = User.objects.all().filter(is_active=True,is_superuser=False)
        # de la lista de usuarios excluye a los usuarios que ya son miembros del proyecto
        for usuario in miembrosLista:
            usuariosLista = usuariosLista.exclude(id=usuario.usuario.id)
        # Excluye el AnonymousUser
        usuariosLista = usuariosLista.exclude(username="AnonymousUser")
        # Excluye los usuarios Administradores
        for admin in User.objects.filter(groups__name="Administrador"):
            usuariosLista = usuariosLista.exclude(id=admin.id)
        # Crea el contexto user_list con la lista de usuarios
        context['user_list'] = usuariosLista
        # Crea el contexto rol_list excluyendo a los roles que no poseen permisos de proyecto
        context['rol_list'] = Group.objects.all().exclude(~Q(permissions__content_type__model="permiso"))
        return context

    def get_success_url(self):
        id_proyecto_ = self.object.proyecto.id
        return reverse_lazy("proyecto:miembro:listar", kwargs={'pk': id_proyecto_})


"""
el miembro esta autorizado puede ver
la lista de miembros del proyecto
en el cual especifica el usuario,
el rol que posee en el proyecto,
las horas que trabaja

ademas se modifican los metodos 
query_set, get_context_data 
para personalizar y mantener 
los datos en estado correcto
"""


class ListarMiembro(ListView):
    model = Miembro
    template_name = 'miembro/Listar_Miembro.html'
    paginate_by = 10

    def get_queryset(self):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['pk'])
        return Miembro.objects.filter(proyecto=self.proyecto)

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['proyecto'] = Proyecto.objects.get(id=self.kwargs['pk'])
        return context


"""
el miembro esta autorizado puede
 eliminar miembros del proyecto

ademas se modifican los metodos
 get_object y get_success_url
para personalizar y mantener 
los datos en estado correcto
"""


class EliminarMiembro(DeleteView):
    model = Miembro
    template_name = 'miembro/Eliminar_miembro.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        queryset = queryset.filter(id=self.kwargs['ide'])
        obj = queryset.get()
        return obj

    def get_success_url(self):
        idProyecto = self.kwargs['pk']
        return reverse_lazy("proyecto:miembro:listar", kwargs={'pk':idProyecto})

    def get_context_data(self, **kwargs):
        context = super(DeleteView, self).get_context_data(**kwargs)
        context['proyecto'] = Proyecto.objects.get(id=self.kwargs['pk'])
        return context



"""
el miembro esta autorizado puede
 modificar miembros del poryecto
ya sea el usuario,
el rol que posee en el proyecto,
las horas que trabaja

ademas se modifican los metodos 
get_object, get_context_data y
get_success_url para personalizar y 
mantener los datos en estado correcto
"""

class ModificarMiembro(UpdateView):
    model = Miembro
    fields = ['rolProyecto', 'horasDeTrabajo']
    template_name = 'miembro/Modificar_Miembro.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        queryset = queryset.filter(id=self.kwargs['id_'])
        obj = queryset.get()
        return obj

    def get_context_data(self, **kwargs):
        context = super(UpdateView, self).get_context_data(**kwargs)
        context['proyecto'] = Proyecto.objects.get(id=self.kwargs['pk'])
        context['rol_list'] = Group.objects.all().exclude(~Q(permissions__content_type__model="permiso"))
        return context

    def get_success_url(self):
        idProyecto = self.kwargs['pk']
        return reverse_lazy("proyecto:miembro:listar", kwargs={'pk': idProyecto})

"""
se utiliza y modifica la funcion has_perm para verificar los permisos del usuario
"""


def has_perm(user, perm, proy_id):
    has = user.has_perm(perm)
    has |= user.has_perm(perm, Proyecto.objects.get(id=proy_id))
    return has

""""
funcion ver_productBacklog verifica 
permisos para ver el product backlog:
* si el miembro esta autorizado se le da 
acceso para ver el product backlog del Proyecto
* si no tiene esos permisos se le
 informa que no posee permisos
"""
@login_required()
def ver_productBacklog(request, *args, **kwargs):

    # `Return:` HttpResponse de acuerdo al caso.
    has_permission = request.user.has_perm('proyecto.ver_productBacklog')
    print("h product backlog ver")
    print(has_permission)
    has_permission |= request.user.has_perm('proyecto.ver_productBacklog', Proyecto.objects.get(id=kwargs['pk']))
    print(has_permission)
    if has_permission:
        return ProductBacklog.as_view()(request, *args, **kwargs)
    else:
        return HttpResponse("<html><h1><p>No posee permisos</p></h1></html>")


"""
el miembro que esta autorizado puede 
visualizar el product backlog
ya sea el usuario,
el rol que posee en el proyecto,
las horas que trabaja

ademas se modifican los metodos 
get_queryset, get_context_data 
para personalizar y mantener 
los datos en estado correcto
"""


class ProductBacklog(ListView):
    model = US
    template_name = 'proyecto/ProductBacklog.html'
    paginate_by = 10

    def get_queryset(self):
        """
        `Override:` personaliza la lista de user stories a fin de proyectar solo los

templates/miembro/Añandir_miembro.html
{% extends 'base/proyecto.html' %}

{% block title %}
     Agregar Miembro
{% endblock %}

{% block content %}
    <div class="container center-block">
        <form method="post">
        {% csrf_token %}
        {% if user_list %}
            <h2 align="center"> Agregar integrante al proyecto {{ proyecto.nombre }}</h2>

            <div class="col-md-8 col-md-offset-1">
                <tr>
                    <th><label for="id_usuario">Usuario:</label></th>
                    <td>
                        <select name="usuario" id="id_usuario" style="width: 200px;" class="col-md-offset-2" required>
                            <option value="" selected> </option>
                        {% for usuarios in user_list %}
                            <option value="{{ usuarios.id }}">{{ usuarios.username }}</option>
                        {% endfor %}
                        </select>
                     </td>
                </tr>
            </div>

            <div class="col-md-8 col-md-offset-1">
                <tr>
                    {% if rol_list %}
                        <th><label for="id_rolProyecto">Rol en Proyecto:</label></th>
                        <td>
                            <select name="rolProyecto" id="id_rolProyecto" style="width: 200px;" class="col-md-offset-1" required>
                                <option value="" selected> </option>
                                    {% for rol in rol_list %}
                                        <option value="{{ rol.id }}">{{ rol.name}}</option>
                                    {% endfor %}
                            </select>
                        </td>
                    {% else %}
                        <label>Rol en Proyecto:     Necesita crear rol de proyecto para poder asignar a los miembros</label>
                    {% endif %}
                </tr>
            </div>
            <div class="col-md-8 col-md-offset-1">
                <tr>
                    <th>
                        <label for="id_horasDeTrabajo">Horas de trabajo:</label>
                    </th>
                    <td><input type="number" name="horasDeTrabajo" value="4" min="1" max="10" style="width: 70px" id="id_horasDeTrabajo" required /></td>
                </tr>
            </div>

            <div class="row"></div><br>

            <div class="col-md-8 col-md-offset-1">
                <div class="form-group">
                    <a class= "btn btn-danger" href="/proyecto/{{ proyecto.id }}/miembro">Cancelar</a>
                    {% if rol_list %}
                        <button class="btn btn-primary" type="submit">Guardar</button>
                    {% else %}
                        <button disabled class="btn btn-primary" type="submit">Guardar</button>
                    {% endif %}
                </div>
            </div>
        {% else %}
            <h1>No hay registro de Miembros en el proyecto</h1>
        {% endif %}
        </form>
    </div>
{% endblock %}

templates/miembro/Eliminar_miembro.html
{% extends 'base/proyecto.html' %}

{% block title %}
    Eliminar Miembro
{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
    <div class="container center-block">
        <p> </p>
        <h3>Confirmacion de expulsion</h3>
	    <h4>¿Desea expulsar al usuario {{ object.usuario.username }} del proyecto {{ proyecto.nombres }}?</h4>
	    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
        <a class= "btn btn-default" href="/proyecto/{{ proyecto.id }}/miembro">Cancelar</a>
    </div>
</form>
{% endblock %}

templates/miembro/Listar_Miembro.html
{% extends 'base/proyecto.html' %}

{% block title %}
    Proyecto | Miembros
{% endblock %}

{% block content %}
<div class="container">

<table class="table table-bordered">
    <div><p> </p></div>
    <a class= "btn btn-default" href="/proyecto/{{ proyecto.id }}/detalle"> Volver al proyecto</a>

    <div><p> </p></div>
    <thead>
		<tr>
            <td>Id</td>
			<td>Usuario</td>
            <td>Rol en Proyecto</td>
            <td>Cantidad de horas de trabajo (diarias/promedio)</td>
            <td>Opciones</td>
		</tr>

</thead>
    <tbody>
        <div></div>

		{% if object_list %}
		    {% for Miembro in object_list %}
		    <tr>
                <td>{{ Miembro.id }}</td>
			    <td>{{ Miembro.usuario.username }}</td>
                {% if Miembro.rolProyecto.name == None %}
                    <td>
                        <u>
                            <i>No posee Rol de Proyecto</i>
                        </u>
                    </td>
                {% else %}
                    <td>{{ Miembro.rolProyecto.name}}</td>
                {% endif %}
                <td>{{ Miembro.horasDeTrabajo }}</td>
			    <td>
				    <a class="btn btn-primary" href= "modificar/{{Miembro.id}}">Modificar</a>
				    <a class="btn btn-danger" href= "eliminar/{{Miembro.id}}">Eliminar</a>
			    </td>
		    </tr>
		    {% endfor %}

		{% else %}
		    <h2>No hay registros de Miembro en el Proyecto</h2>
            <div><p> </p></div>
		{% endif %}
</tbody>
</table>
<ul class="pagination">
	<li class="page-item">
		{% if page_obj.has_previous %}
       	 <a class="page-link" aria-label="Anterior" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a class="page-link" aria-label="Siguiente" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
    	{% endif %}
    </li>
</ul>
</div>

{% endblock %}

templates/miembro/Modificar_Miembro.html
{% extends 'base/proyecto.html' %}

{% block title %}
    Miembro | Modificar: {{ Miembro.usuario }}
{% endblock %}

{% block content %}
<div class="container pt-3 ">
    <form method="post">
        {% csrf_token %}

        <h3>Miembro: {{ object.usuario.username }} en {{ proyecto.nombre }}</h3>

        <div>
            <tr>
                <th><label for="id_rolProyecto">Rol en Proyecto:</label></th>
                <td>
                    <select name="rolProyecto" id="id_rolProyecto" required>
                        {% if Miembro.rolProyecto.name == None %}
                            <option value="" selected></option>
                        {% endif %}
                        {% for rol in rol_list %}
                            <option value="{{ rol.id }}"
                                    {% if rol.id == object.rolProyecto_id %}
                                        selected
                                    {% endif %}>
                                {{ rol.name }}
                            </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
        </div>

        <div>
            <tr>
                <th>
                    <label for="id_horasDeTrabajo">Horas de trabajo:</label>
                </th>
                <td>
                    <input type="number" id="id_horasDeTrabajo" min="1" name="horasDeTrabajo" value="{{ object.horasDeTrabajo }}" required /></td>
            </tr>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <a class= "btn btn-danger" href="/proyecto/{{ proyecto.id }}/miembro/">Cancelar</a>
                    <button class="btn btn-primary "type="submit">Guardar</button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}